export const CONTENT_UI_LABELS = Object.freeze({
  controls: {
    openTranscript: 'Open Transcript',
    openingTranscript: 'Opening transcript...',
    translate: 'Translate',
    translateAgain: 'Translate Again',
    refine: 'Refine',
    refined: 'Refined',
    startingTranslation: 'Starting...',
    startingRefine: 'Refining...',
    translating: 'Translating...',
    cancel: 'Cancel',
    cancelling: 'Cancelling...',
    openHint: 'Open transcript to begin.',
    readyHint: 'Ready to translate.',
    runningHint: 'Translating...',
    completedHint: 'Done.',
    idleHint: '',
  },
  monitor: {
    title: 'YT AI Translator Rebuild',
    slice: 'Slice',
    youtube: 'YouTube',
    task: 'Task',
    progress: 'Progress',
    target: 'Target',
    updated: 'Updated',
    open: 'Open',
    translate: 'Translate',
    cancel: 'Cancel',
  },
  surface: {
    title: '',
    export: 'Export',
    import: 'Import',
    waiting: '',
    ready: '',
    cachedReady: 'Cached',
    refinedReady: 'Refined',
    importedReady: 'Imported',
    partialResumeAvailable: 'Partial cache available. Enable Resume mode or import JSON.',
    empty: '',
    overlayPlaceholder: '',
  },
  status: {
    idle: '',
    openingTranscript: 'Opening transcript...',
    transcriptReady: 'Ready',
    startingTranslation: 'Preparing...',
    startingRefine: 'Refining...',
    running: 'Translating...',
    retrying: 'Retrying...',
    completed: 'Done',
    failed: 'Failed',
    cancelled: 'Cancelled',
  },
} as const);
